# Generated by Django 3.1.7 on 2022-01-04 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLookup',
            fields=[
                ('activity_number', models.AutoField(primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('each', 'Each'), ('lbs.', 'Pounds'), ('oz', 'Ounces'), ('Serving', 'Servings'), ('min', 'Minutes'), ('day', 'Per Day'), ('weekly', 'Per Week')], default='each', max_length=10, verbose_name='Unit Type')),
                ('point_value', models.FloatField(verbose_name='Points Per Unit')),
                ('daily_point_limit', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_number', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('user_auth_obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('record_number', models.AutoField(primary_key=True, serialize=False)),
                ('record_date', models.DateTimeField()),
                ('number_recorded', models.IntegerField()),
                ('points', models.IntegerField()),
                ('activity_num', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='FeelGreat_main.activitylookup')),
                ('user_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FeelGreat_main.userprofile')),
            ],
        ),
    ]
