# Generated by Django 3.1.7 on 2022-01-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeelGreat_main', '0003_auto_20220117_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylookup',
            name='act_description',
            field=models.TextField(default='Description pending.'),
        ),
        migrations.AlterField(
            model_name='activitylookup',
            name='value_type',
            field=models.CharField(choices=[('each', 'Each'), ('lbs.', 'Pounds'), ('oz', 'Ounces'), ('Serving', 'Servings'), ('min', 'Minutes'), ('day', 'Per Day'), ('weekly', 'Per Week'), ('daily_calendar', 'Daily Special')], default='each', max_length=20, verbose_name='Unit Type'),
        ),
    ]
